"""A minimal, fully-commented example Program.

This file is a **teaching template**, not a real game. Copy it to a new module
in ``src/programs/`` and adapt it to build your own mini-game. It exercises every
part of the :class:`~src.programs.base.Program` contract a new author needs:
events, per-button cooldowns, the ``after()`` scheduler, audio playback, a laser
animation, and quitting back to the menu.

It is registered (so you can launch it with ``python -m src -p ExampleProgram``)
but is intentionally **not** in ``config.GameSelect.MENU``, so it never appears
in the operator menu.

See the "Authoring New Programs" guide for the full walkthrough.
"""
from .base import *
from ..event_loop import *
from ..config import config
from ..animation import random_k_dance


class ExampleProgram(Program):
    """An "echo" toy: each button lights its laser and speaks its number.

    Behaviour:
        * Press button ``n`` -> laser ``n`` turns on and the number ``n`` is
          spoken (rate-limited by a per-button cooldown).
        * Release button ``n`` -> laser ``n`` turns off.
        * Flip either toggle -> a short celebratory laser dance plays.
        * Press the last button (13) -> the program quits back to the menu.
    """

    QUIT_BUTTON = 13
    SPEAK_COOLDOWN_MS = 250

    def __init__(self):
        # Always call super().__init__() first: it registers this instance as a
        # singleton and initialises the tick counter, scheduler and cooldowns.
        super().__init__()

    # -- lifecycle -----------------------------------------------------------
    def start(self):
        """Set up audio and laser state. Called every time the program is
        activated (which may happen more than once over the box's lifetime)."""
        # Pick a sound bank ("patch"): 14 wavs, one per button. ``numbers``
        # speaks "one".."fourteen".
        self.game.mixer.use_patch("numbers")
        # Background ambience on loop (loops=-1 = forever).
        self.game.mixer.load_music("ocean_sounds22050.wav", loops=-1)
        self.game.mixer.set_music_volume(0.6)
        # Start with all lasers off.
        self.game.lasers.set_word(0)

    def quit(self):
        """Tidy up, then hand control back to the state machine.

        The base ``quit`` advances the current context (returning to GameSelect
        for a single-program launch). The StateMachine also tears down audio,
        animations, lasers and pending callbacks, so explicit cleanup here is
        only for anything unusual you started.
        """
        super().quit()

    # -- per-frame update ----------------------------------------------------
    def update(self, dt):
        """Called once per frame whether or not input changed. ``dt`` is in ms.

        Args:
            dt: Milliseconds elapsed since the previous frame.
        """
        # super().update() runs cooldown/scheduler bookkeeping and advances the
        # tick counter -- always call it.
        super().update(dt)

        # Drain this frame's input events. ``events.get()`` yields the queued
        # ButtonDown/ButtonUp/ToggleOn/ToggleOff events generated by the input
        # manager from the latest hardware read.
        for event in events.get():
            if event.type == EventType.BUTTON_DOWN:
                self._on_button_down(event.key)
            elif event.type == EventType.BUTTON_UP:
                self._on_button_up(event.key)
            elif isinstance(event, ToggleEvent):
                self._on_toggle()

    # -- handlers ------------------------------------------------------------
    def _on_button_down(self, button_id):
        if button_id == self.QUIT_BUTTON:
            return self.quit()
        self.game.lasers.turn_on(button_id)
        # Rate-limit speaking so a held/bouncing button doesn't retrigger.
        if button_id not in self.cooldowns:
            self.game.mixer.play_by_id(button_id)
            self.start_cooldown(button_id, ms=self.SPEAK_COOLDOWN_MS)

    def _on_button_up(self, button_id):
        self.game.lasers.turn_off(button_id)

    def _on_toggle(self):
        # ``input_manager.state`` is the latest full input State; ``.toggles`` is
        # the 2-bit toggle value.
        toggles = self.game.input_manager.state.toggles
        print("toggles now:", toggles)
        # Animations are fire-and-forget: build one and call .start(). The global
        # Animation manager drives it each frame and clears the lasers when done.
        random_k_dance(k=3, fps=8, dur=1.5).start()
        # Example of deferring work: speak "one" half a second from now.
        self.after(500, self.game.mixer.play_by_id, 0)


# Instantiate the singleton so it registers itself with the StateMachine. Every
# program module must do this at import time.
ExampleProgram()
